include project.cfg

BITFILE = $(PROJECT).bin

default: $(BITFILE)

$(PROJECT).json: $(VSOURCE)
	@mkdir -p build
	yosys -p 'synth_ice40 -top $(TOPLEVEL) -json build/$(PROJECT).json' $(VSOURCE)

$(PROJECT).asc: $(PROJECT).json $(CONSTRAINTS)
	nextpnr-ice40 --hx8k --package ct256 --pcf $(CONSTRAINTS) --asc build/$(PROJECT).asc --json build/$(PROJECT).json

$(PROJECT).bin: $(PROJECT).asc
	icetime -d hx8k -c $(PIXCLK) build/$(PROJECT).asc
	icepack build/$(PROJECT).asc build/$(PROJECT).bin
