include project.cfg

BITFILE = $(PROJECT).bin

default: $(BITFILE)

$(PROJECT).blif: $(VSOURCE)
	@mkdir -p build
	yosys $(YOSYS_OPTS) -p 'synth_ice40 -top $(TOPLEVEL) -blif build/$(PROJECT).blif' $(VSOURCE)

$(PROJECT).asc: $(PROJECT).blif $(CONSTRAINTS)
	arachne-pnr -d 8k -p $(CONSTRAINTS) -o build/$(PROJECT).asc build/$(PROJECT).blif

$(PROJECT).bin: $(PROJECT).asc
	icetime -d hx8k -c 25 build/$(PROJECT).asc
	icepack build/$(PROJECT).asc build/$(PROJECT).bin
