default:
	$(error BOARD not defined)

papid:
	$(MAKE) CHIP=spartan6 BOARD=papiduo -f ./Makefile.xilinx

papip:
	$(MAKE) CHIP=spartan6 BOARD=papipro -f ./Makefile.xilinx

ico:
	$(MAKE) BOARD=icoboard -f ./Makefile.icestorm

clean:
	rm -rf build
